baseURL: "https://luce-breuil.github.io" 
title: Luce Breuil
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 2
        - name: Papers
          url: papers/
          weight: 2

params:
    description: "This website hosts Luce Breuil research papers, curriculum vitae, and contact information."
    author: Luce Breuil
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["CV","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luce Breuil
          subtitle: 'I am a 2nd year PhD student in Applied Mathematics at CMAP at Ecole Polytechnique. I work under the supervision of <a href="https://team.inria.fr/merge/fr/marie-doumic/" style="text-decoration: underline;" target="_blank">M.Doumic</a> and <a href="https://www.math.univ-paris13.fr/~kaakai/" style="text-decoration: underline;" target="_blank">S.Kaakaï</a>, in collaboration with <a href="https://michaelrera.github.io/" style="text-decoration: underline;" target="_blank">M.Rera</a>. <br> My work focuses on mathematical biology, at the interface of stochastic processes, statistics and PDEs. Currently, I am working on modeling aging as a 2-phase process inspired by the <a href="https://pubmed.ncbi.nlm.nih.gov/23236133/" style="text-decoration: underline;" target="_blank">Smurf phenotype</a> discovered by Michael Rera. I am a part of the INRIA-CMAP team <a href="https://team.inria.fr/merge/fr/" style="text-decoration: underline;" target="_blank">Merge</a>. <br> **email**: luce.breuil@polytechnique.edu'
          imageUrl: "IMG_5350.jpeg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Papers
              url: papers/
            - name: CV
              url: cv.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Luce Breuil"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
