baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Luce Breuil
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
         - name: CV
          url:cv/
          weight: 2
        - name: Papers
          url: papers/
          weight: 2

params:
    description: "This website hosts Luce Breuil's research papers, curriculum vitae, and contact information."
    author: Luce Breuil
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: "CV',"papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luce Breuil
          subtitle: "I am PhD student in Applied Mathematics at CMAP at Ecole Polytechnique. I work under the supervision of M.Doumic and S.Kaakai, in collaboration with M.Rera"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: CV
              url: CV/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:luce.breuil@polytechnique.edu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Luce Breuil"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
